# Generated by Django 4.2.16 on 2024-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0005_recipeingredient_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='desc',
        ),
        migrations.AddField(
            model_name='recipe',
            name='desc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
