# Generated by Django 4.2.16 on 2024-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0003_recipeingredient_unique_recipes_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
